version: '2'

services:

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Tokyo"
        ports:
            - 3306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql

    web:
        build:
            context: .
            dockerfile: ./ruby/Dockerfile
        volumes:
            - ./ruby:/myapp
        ports:
            - 3000:3000
        links:
            - db:dbhostname
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
