# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b2809b9230d4be5de258cb4e76c718516a851567740cef34fd2a57a62c175f451aeb74d30cf3ce2806ffe56f7b04a0a49af41554c8ad7298640be9a822c55dc

test:
  secret_key_base: 7b33e9423f3f0d96b07fb42544de05a37164d4eabdc82cd93c9a995b8c43540a2eff853b2ceb2f221a3c9334d9bdb8e95cd28c46bba5ff7d1a0a46ba921531db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
